### ISSUE TITLE
Bytes filters doesn't work for '0'

### ISSUE THREAD

**Issue by paucls** [exceptionless/angular-filters#2]
The bytes filter works fine parsing numbers or strings
{{55 | bytes}}  //OK 55
{{'55' | bytes}}  //OK 55
{{0 | bytes}}  //OK 0

but fails for 
{{'0' | bytes}}  //Error NaN 

It would be nice to handle that case in the filter. And for other case don't show anything.

**Comment by niemyjski** [comment]
Thanks for reporting this issue. I've fixed it in the following commit: https://github.com/exceptionless/angular-filters/commit/fbc0c04d5122314f8ea203484775d62efc7dff61
